### ISSUE TITLE
Raspberry Pi Zero 2 

### ISSUE THREAD

**Issue by samratswami** [showmewebcam/showmewebcam#203] opened 2022-08-05 07:46 UTC
I tried installing this on Raspberry Pi Zero 2 but its not booting. While starting i can just see one blink. Tried with 1.3 version and its working fine. Please help.

**Comment by dgsiegel** [comment] 2022-08-05 09:23
Duplicate of #168

**Closed by dgsiegel** 2022-08-05 09:23 UTC
