### ISSUE TITLE
"Your webcam at your service!" arrives late.

### ISSUE THREAD

**Issue by akseidel** [showmewebcam/showmewebcam#106] opened 2021-02-17 23:04 UTC
When making the serial connection using screen, the greeting "Your webcam at your service!" is supposed to output before the login process starts. I have observed over time on both Apple OSX and Linux (Raspbian) systems the first parts of the greeting line being injected into the the first part (the user line) of the login process. This messes up the login process. One has to get the login process to restart itself.

At first this condition would be sporadic, but now it consistently happens.

**Comment by dgsiegel** [comment] 2021-02-18 00:05
Duplicate of #37

**Closed by dgsiegel** 2021-02-18 00:05 UTC
