### ISSUE TITLE
No webcam is detected after updating to macOS 12.0.1

### ISSUE THREAD

**Issue by bl1nk** [showmewebcam/showmewebcam#164] opened 2021-10-27 19:19 UTC
Today I updated two of my MacBooks to macOS 12.0.1. When connecting my showmewebcam-equipped Raspberry Pi Zero W no devices are detected in any application. This happened on an Intel MacBook Pro and a M1 MacBook Air so at least it is not related to the architecture. 

In Console.app I could find some errors that might be related.

```
default	21:00:03.358719+0200	kernel	set CameraAssistantBundleID : com.apple.cmio.uvcassistantextension
default	21:00:03.358917+0200	kernel	set CameraAssistantBundleID : com.apple.cmio.uvcassistantextension
default	21:00:03.359833+0200	kernelmanagerd	Received kext load notification: com.apple.DriverKit-UVCUserService
default	21:00:03.359627+0200	UVCAssistant	UVCExtensionProvider: [0x156f04100] Found : 0x10000c246 bundleID com.apple.cmio.uvcassistantextension
default	21:00:03.359859+0200	kernelmanagerd	Received kext load notification: com.apple.DriverKit-UVCUserService
default	21:00:03.359731+0200	UVCAssistant	UVCExtensionProvider: [0x156f04100] VID 1d6b PID : 104 AppleCameraSupport No
default	21:00:03.359816+0200	UVCAssistant	UVCExtensionProvider: [0x156f04100] Association ID for service 10000c246 : 0
default	21:00:03.574901+0200	UVCAssistant	UVCExtensionDevice:0x0 [0x156e18de0] Association ID for service 10000c246 : 0
default	21:00:03.575129+0200	UVCAssistant	UVCExtensionDevice:0x0 [0x156e18de0] LocalizedDeviceName Piwebcam manufacturerName Show-me Webcam Project UUID 00000000-0224-2000-1D6B-000001040000
default	21:00:03.575254+0200	UVCAssistant	UVCExtensionDevice:0x0 [0x156e18de0] Post PowerLog {
    "VDCAssistant_Device_GUID" = "00000000-0224-2000-1D6B-000001040000";
    "VDCAssistant_Power_State" = Off;
}
default	21:00:03.575395+0200	UVCAssistant	boot args [enableCameraExtension : 0]
default	21:00:03.575457+0200	UVCAssistant	UVCUSBDevice: 0x0 [0x16010cef0] -[UVCUSBDevice initWithInterface:queue:streamDataHandler:stateNotificationHandler:]
default	21:00:03.575536+0200	UVCAssistant	Device : 10000c240
default	21:00:03.575874+0200	UVCAssistant	UVCUSBDevice: 0x10000c240 [0x16010cef0] CurrentConfiguration : 2 NumberOfConfigurations: 1
error	21:00:03.575923+0200	UVCAssistant	UVCUSBDevice: 0x10000c240 [0x16010cef0] Failed to get configuration descriptor for interface
default	21:00:03.575968+0200	UVCAssistant	UVCUSBDevice: 0x10000c240 [0x16010cef0] -[UVCUSBDevice dealloc]
error	21:00:03.576018+0200	UVCAssistant	UVCExtensionDevice:0x0 [0x156e18de0] Failed to setup UVC Device
default	21:00:03.576064+0200	UVCAssistant	UVCExtensionDevice:0x0 [0x156e18de0] -[UVCExtensionDevice dealloc]
default	21:00:03.576112+0200	UVCAssistant	UVCExtensionProvider: [0x156f04100] create device (null)
error	21:00:03.576153+0200	UVCAssistant	UVCExtensionProvider: [0x156f04100] Failed to create CMIO device for UVC device 10000c246
```

I am able to connect to the serial interface on `/dev/tty.usbmodemXXXXXX` using `screen`.

Happy to help to debug this further when given instructions.

**Comment by tomjtobin** [comment] 2021-11-01 16:30
Is it deciding based on productId/vendorID of the USB device? Are there known good values of productId/vendorID that would make it work?

**Comment by tomjtobin** [comment] 2021-11-01 16:53
Is this the problem: https://eclecticlight.co/2019/03/23/apple-is-killing-quicktime-7-in-macos-10-15-convert-old-media-now/ because there's another note that mjpeg isn't working at all: https://forum.manycam.com/t/install-macos-monterey-and-i-can-not-access-my-usb-camera-anymore/5750

**Comment by RTHPJM** [comment] 2021-11-01 17:23
> Is this the problem: https://eclecticlight.co/2019/03/23/apple-is-killing-quicktime-7-in-macos-10-15-convert-old-media-now/ because there's another note that mjpeg isn't working at all: https://forum.manycam.com/t/install-macos-monterey-and-i-can-not-access-my-usb-camera-anymore/5750

Hi tomjtobin,

There are a few specific VID/PID matching pairs in the Info.plist file of com.apple.DriverKit-UVCUserService.dext. They’re obviously more specific and seem to invoke uvcassistantextension with parameters to exclude certain resolutions. It doesn’t really help us in my opinion. We’re expecting “generic” support for UVC cameras in a similar fashion to earlier versions of MacOS. My guess is uvcassistantextension is “broken”.

**Comment by bl1nk** [comment] 2021-11-02 21:12
> SMW has a video formats configuration file. I’ll try turning off mjpeg and use uncompressed. I’ll report back later…

I just tried that on `v1.90` with a `/boot/video_formats.txt` containing

```
uncompressed 1280 720
uncompressed 1920 1080
```

After rebooting the Pi no `/dev/tty.usbmodemXXXXXX` device is created anymore.

**Comment by RTHPJM** [comment] 2021-11-02 23:42
> > SMW has a video formats configuration file. I’ll try turning off mjpeg and use uncompressed. I’ll report back later…
> 
> I just tried that on `v1.90` with a `/boot/video_formats.txt` containing
> 
> ```
> uncompressed 1280 720
> uncompressed 1920 1080
> ```
> 
> After rebooting the Pi no `/dev/tty.usbmodemXXXXXX` device is created anymore.

Hi bl1nk,

I had similar issues. If /boot/video_formats.txt contains only uncompressed entries, then the uvc-gadget does not start. (uvc-gadget is responsible for the camera-to-pi, pi-to-host-over-USB, AND the serial-to-host-over-USB).

If I have at least one mjpeg line, then uvc-gadget starts. I guess it could be.a bug with uvc-gadget?

Also, I'm using a pi zero w, which has USB2 interfaces, this limits the maximum data rate to 480Mbits/s (60Mbytes/s).
Uncompressed format is necessarily harder on the transfer rate, so high X/Y resolutions are not going to be usable!

I have my video_formats.txt file with just two entries:
uncompressed 640 480
mjpeg 640 480

and uvc-gadget does start, however, MacOS Monterey still does not see the camera. (But maybe I'm still defaulting to mjpeg?)

**Comment by mlinton** [comment] 2021-11-03 20:10
Built an image using the nightly build (from source), modified the video_formats.txt file to including only uncompressed formats:

Still getting the issues with the Macos on connection:
```default	14:08:54.709820-0600	kernelmanagerd	Received kext load notification: com.apple.UVCService
default	14:08:54.709851-0600	kernelmanagerd	Received kext load notification: com.apple.DriverKit-UVCUserService
default	14:08:54.710242-0600	kernel	set CameraAssistantBundleID : com.apple.cmio.uvcassistantextension
default	14:08:54.710489-0600	UVCAssistant	UVCExtensionProvider: [0x7fb7822040a0] Found : 0x100006c45 bundleID com.apple.cmio.uvcassistantextension
default	14:08:54.710613-0600	UVCAssistant	UVCExtensionProvider: [0x7fb7822040a0] VID 1d6b PID : 104 AppleCameraSupport No
default	14:08:54.710716-0600	UVCAssistant	UVCExtensionProvider: [0x7fb7822040a0] Association ID for service 100006c45 : 0
default	14:08:54.710949-0600	kernelmanagerd	Received kext load notification: com.apple.DriverKit-UVCUserService
default	14:08:54.711195-0600	kernel	set CameraAssistantBundleID : com.apple.cmio.uvcassistantextension
default	14:08:54.918756-0600	UVCAssistant	UVCExtensionDevice:0x0 [0x7fb782519900] Association ID for service 100006c45 : 0
default	14:08:54.918948-0600	UVCAssistant	UVCExtensionDevice:0x0 [0x7fb782519900] LocalizedDeviceName UVC Camera manufacturerName Show-me Webcam Project UUID 00000000-1430-0000-1D6B-000001040000
default	14:08:54.919060-0600	UVCAssistant	UVCExtensionDevice:0x0 [0x7fb782519900] Post PowerLog {
    "VDCAssistant_Device_GUID" = "00000000-1430-0000-1D6B-000001040000";
    "VDCAssistant_Power_State" = Off;
}
default	14:08:54.919198-0600	UVCAssistant	boot args [enableCameraExtension : 0]
default	14:08:54.919265-0600	UVCAssistant	UVCUSBDevice: 0x0 [0x7fb785d06d20] -[UVCUSBDevice initWithInterface:queue:streamDataHandler:stateNotificationHandler:]
default	14:08:54.919320-0600	UVCAssistant	Device : 100006c37
default	14:08:54.919574-0600	UVCAssistant	UVCUSBDevice: 0x100006c37 [0x7fb785d06d20] CurrentConfiguration : 2 NumberOfConfigurations: 1
error	14:08:54.919610-0600	UVCAssistant	UVCUSBDevice: 0x100006c37 [0x7fb785d06d20] Failed to get configuration descriptor for interface
default	14:08:54.919651-0600	UVCAssistant	UVCUSBDevice: 0x100006c37 [0x7fb785d06d20] -[UVCUSBDevice dealloc]
error	14:08:54.919681-0600	UVCAssistant	UVCExtensionDevice:0x0 [0x7fb782519900] Failed to setup UVC Device
default	14:08:54.919709-0600	UVCAssistant	UVCExtensionDevice:0x0 [0x7fb782519900] -[UVCExtensionDevice dealloc]
default	14:08:54.919739-0600	UVCAssistant	UVCExtensionProvider: [0x7fb7822040a0] create device (null)
error	14:08:54.919766-0600	UVCAssistant	UVCExtensionProvider: [0x7fb7822040a0] Failed to create CMIO device for UVC device 100006c45
```

**Comment by tomjtobin** [comment] 2021-11-03 20:19
I didn't see anything on https://openradar.appspot.com/ that would mean there was a logged defect with Apple for this, which I'd expect if it was every mjpeg camera.
Also, however, my internal MacBook Pro camera has also been going dark (and no green light) on Zoom and other apps, so there is something very flakey with cameras in 12.0.1

**Comment by mseri** [comment] 2021-11-03 21:04
I have taken out an old xbox 360 webcam which used to work fine with mac os, it is also not appearing at all on 12.0.1

**Comment by RTHPJM** [comment] 2021-11-04 20:13
> I didn't see anything on https://openradar.appspot.com/ that would mean there was a logged defect with Apple for this, which I'd expect if it was every mjpeg camera.
> Also, however, my internal MacBook Pro camera has also been going dark (and no green light) on Zoom and other apps, so there is something very flakey with cameras in 12.0.1

I’ve sent “feedback” via the feedback web site. It might result in Apple opening a bug ticket internally (which might then find it’s way through to openradar). I’ve also started [a thread on the Apple Developer forums](https://developer.apple.com/forums/thread/693784)  to see if we can coordinate reports from others.

**Comment by RTHPJM** [comment] 2021-11-04 20:15
I think this is firmly an issue for Apple, and not necessarily an issue with ShowMeWebcam / UVC-Gadget…

**Comment by RTHPJM** [comment] 2021-11-04 20:18
> Still getting the issues with the Macos on connection:
> 
> ```
> default	14:08:54.709851-0600	kernelmanagerd	Received kext load notification: com.apple.DriverKit-UVCUserService
> default	14:08:54.710242-0600	kernel	set CameraAssistantBundleID : com.apple.cmio.uvcassistantextension
> default	14
> ```

@mlinton, are you using a beta version of Monterey or the release version?

**Comment by RTHPJM** [comment] 2021-11-05 11:10
> Built an image using the nightly build (from source), modified the video_formats.txt file to including only uncompressed formats:

I also ran some tests. My purpose was to try and prove or disprove the theory that MJPEG was the issue. Like @mlinton I used a build of SMW that supports uncompressed configurations...

The baseline for my tests was the default configuration running on Big Sur. The default video_formats.txt file has entries for mjpeg only. On Big Sur we know this works. The visual result is very smooth video in apps like FaceTime.

Next I copied the video_formats.txt file to the /boot folder, edited it to comment out all the mjpeg lines, then I added in a single uncompressed line. I figured it would be best to specifically enable one format at a time. Also, I had read somewhere that dimensions for YUV format should be clamped to multiples of 32, therefore I tried to use resolutions that naturally fit multiples of 32. My first entry was:

uncompressed 640 480

Save, power off, power on. This resolution worked really well, surprisingly well (on Big Sur). Since my goal was to prove the use of uncompressed, I then edited the video_formats.txt file a second time, comment out the 640x480 line, add a new line:

uncompressed 1280 720

Save, power off, power on. This resolution worked but is noticeably "choppy" because the frame rate becomes much lower due to the larger volume of data that needs to be transmitted over USB2 per frame. This is good! It shows a distinct difference in performance between default (mjpeg) configuration, and uncompressed configuration. This means that I can be confident that SMW is sending an uncompressed only stream and that FaceTime still renders the images (on Big Sur). Armed with this knowledge I could proceed to Monterey knowing that the current configuration (uncompressed 1280 720) should work in Monterey IF the issue were mjpeg related.

I therefore reboot my Mac into Monterey 12.0.1 production release. Monterey still cannot see the camera (No video capture devices were found.). To be complete, I then edited the video_formats.txt files again, comment out the 1280x720 line, enable the uncompressed 640x480 line. Save, power off, power on. Monterey still does not find the camera. 

_Thus, I believe we can say that the issue is NOT related to Monterey (or any version of Mac OS) dropping support for mjpeg._

I performed other tests too, looking at the way Big Sur behaves verses Monterey. IOKit matching seems to be fine. I noticed VDCAssistant binds under certain configurations, uvcassistantextension binds under other circumstances. I need to do some more testing, I'll report back any findings later...

**Comment by tomjtobin** [comment] 2021-11-05 18:40
One thing from looking at this, one of the first messages is the:
UVCAssistant Failed to get configuration descriptor for interface
and just before this there is 
default	15:05:12.225593-0700	UVCAssistant	UVCUSBDevice: 0x100435663 [0x7f86c600d0e0] CurrentConfiguration : 2 NumberOfConfigurations: 1
I noticed in multi-gadget.sh that the config directory lists c.2 as the config container. Is it just Apple reading there being 1 configuration and trying to get it from c.1?
That config ends up created in /sys/kernel/config/usb_gadget/piwebcam/configs
I tried to change this but I'm not ready to re-create the image right now.
The doc uses c.1 as the default: https://www.kernel.org/doc/Documentation/usb/gadget_configfs.txt
I'm not clear why c.2 would be used as the only config

**Comment by stoggi** [comment] 2021-11-07 22:38
@tomjtobin You are onto it!

I rebuilt the image with the following changes:

```
index 0398d39..fc9f1cf 100755
--- a/package/piwebcam/multi-gadget.sh
+++ b/package/piwebcam/multi-gadget.sh
@@ -30,19 +30,19 @@ echo 0x01 > bDeviceProtocol
 echo 0x40 > bMaxPacketSize0

 mkdir -p strings/0x409
-mkdir -p configs/c.2
-mkdir -p configs/c.2/strings/0x409
+mkdir -p configs/c.1
+mkdir -p configs/c.1/strings/0x409

 SERIAL=$(cat /sys/firmware/devicetree/base/serial-number)
 echo "$SERIAL"                > strings/0x409/serialnumber
 echo "Show-me Webcam Project" > strings/0x409/manufacturer
 echo "Piwebcam"               > strings/0x409/product
-echo "Piwebcam"               > configs/c.2/strings/0x409/configuration
-echo 500                      > configs/c.2/MaxPower
+echo "Piwebcam"               > configs/c.1/strings/0x409/configuration
+echo 500                      > configs/c.1/MaxPower

 config_usb_serial () {
   mkdir -p functions/acm.usb0
-  ln -s functions/acm.usb0 configs/c.2/acm.usb0
+  ln -s functions/acm.usb0 configs/c.1/acm.usb0
 }

 config_frame () {
@@ -94,7 +94,7 @@ config_usb_webcam () {
   ln -s functions/uvc.usb0/streaming/header/h       functions/uvc.usb0/streaming/class/hs
   ln -s functions/uvc.usb0/control/header/h         functions/uvc.usb0/control/class/fs

-  ln -s functions/uvc.usb0 configs/c.2/uvc.usb0
+  ln -s functions/uvc.usb0 configs/c.1/uvc.usb0
 }

 # Check if camera is installed correctly
```

And can comfirm it works on macOS 12.0.1 and 11.5.2

```
$ system_profiler SPCameraDataType
Camera:

    UVC Camera:

      Model ID: UVC Camera VendorID_7531 ProductID_260
      Unique ID: 0x142000001d6b0104
```

I can view the stream now just fine, at 1080p with mjpeg. It would be interesting to find out why `c.2` was used in the first place, and if changing to `c.1` causes any problems.

**Comment by RTHPJM** [comment] 2021-11-07 23:37
> One thing from looking at this, one of the first messages is the:
> UVCAssistant Failed to get configuration descriptor for interface
> and just before this there is
> default 15:05:12.225593-0700 UVCAssistant UVCUSBDevice: 0x100435663 [0x7f86c600d0e0] CurrentConfiguration : 2 NumberOfConfigurations: 1
> I noticed in multi-gadget.sh that the config directory lists c.2 as the config container. Is it just Apple reading there being 1 configuration and trying to get it from c.1?
> That config ends up created in /sys/kernel/config/usb_gadget/piwebcam/configs
> I tried to change this but I'm not ready to re-create the image right now.
> The doc uses c.1 as the default: https://www.kernel.org/doc/Documentation/usb/gadget_configfs.txt
> I'm not clear why c.2 would be used as the only config

Congrats to @tomjtobin for essentially figuring this out. Thanks to @stoggi for compiling and testing, then making the Pull Request :)

**Comment by htruong** [comment] 2021-11-08 05:20
Thanks everyone. This problem should be fixed in the latest commit. I will figure out how to do a release with this change soon and close the ticket if no one has further troubles!

**Comment by tomjtobin** [comment] 2021-11-08 06:44
Sorry I couldn't come back with the pull request. I had tried reproduce by remounting parts of the filesystem as read-write, using a new trick I learned and using --bind, and mounting directories as read-write, and trying to restart the gadget software without cutting the usb connection. I have to say the toolchain is picky, I tried to build on Mac, didn't get far, tried on a Pi4, got further but not all the way, found the problem led to "you need to use x86 linux to build" and then after a few other errors, finally got that to work today.
Thanks everybody!

**Comment by RTHPJM** [comment] 2021-11-08 11:29
> Sorry I couldn't come back with the pull request. I had tried reproduce by remounting parts of the filesystem as read-write, using a new trick I learned and using --bind, and mounting directories as read-write, and trying to restart the gadget software without cutting the usb connection. I have to say the toolchain is picky, I tried to build on Mac, didn't get far, tried on a Pi4, got further but not all the way, found the problem led to "you need to use x86 linux to build" and then after a few other errors, finally got that to work today.
> Thanks everybody!

HI @tomjtobin, I found it quicker (and perhaps cleaner) to use VirtualBox. Build a Debian/Ubuntu guest and set it up to cross compile as per the [Pi Foundation's recommendation](https://www.raspberrypi.com/documentation/computers/linux_kernel.html#cross-compiling-the-kernel)

HINT: Just **apt install** the dependencies and toolchains. Stop before getting to the kernel sources, there's no need for those further steps, @htruong's buildroot configuration will do all the necessary downloading.

Then following @htruong's compiling guide from the README.md....
Download and unzip the showmewebcam zip file.
Change Directory to the showmewebcam-master folder
Download and unpack the Buildroot system here (rename it to buildroot after extraction)
(Make your modifications to the code base if necessary)
Run the build script

My only caveat is that I used VirtualBox default sizes for the first guest VM, in particular a 20Gb disk allocation. This isn't enough to hold and build the buildroot toolchain as well as the SMW image. Make the disk size 50Gb!

Oh, and I used Ubuntu server rather than desktop, since cross compiling tends to be a terminal-based activity anyway (no need for the GUI!)

**Comment by htruong** [comment] 2021-11-09 00:25
The absolute laziest way to build showmewebcam firmware is that you fork this repository on github and then go to your own repository and go to the action tab. Setup github actions, it will show you the option to build the firmware :) then wait an hour github will build for you.

**Comment by htruong** [comment] 2021-11-09 02:52
Official builds for v1.91 with Monterey support are out, I'm gonna close this ticket now. LMK if this doesn't work.

**Closed by htruong** 2021-11-09 02:52 UTC
